/* eslint-disable */
// @ts-nocheck
/* ══════════════════════════════════════════════════════════════════════════
   The TV loop — generated by tools/port-tv-demo.mjs. Edit the pasted page and
   re-run rather than editing here, or the next run overwrites you.

   Verbatim from the <script> blocks of the pasted standalone page, in their
   original order, wrapped so Angular can run them: a template's <script> tags
   are dropped by the compiler and never execute, which is why the board came
   up empty.

   The blocks are unchanged apart from the device edits the porting script
   applies to the engine — it prints which of them matched on every run.

   @ts-nocheck: this is ES5-era DOM code that predates the project, and typing
   it would mean rewriting it. It is isolated in this one file for that reason.
   ══════════════════════════════════════════════════════════════════════════ */

/**
 * Builds the board into the markup already rendered by app.html and starts the
 * loop. Browser only — it reads window, Date and document.
 *
 * @returns a teardown that stops every timer and frame the loop owns.
 */
export function startTvDemo(): () => void {
  const _timeouts: number[] = [];
  const _intervals: number[] = [];
  const _frames: number[] = [];

  /* The copied code schedules with the bare globals. Shadowing them here — the
     blocks below are nested in this function — records every handle without
     touching a line of that code, so the loop can actually be stopped when the
     component goes away. */
  function setTimeout(fn: any, ms?: number, ...args: any[]): number {
    const id = window.setTimeout(fn, ms, ...args);
    _timeouts.push(id);
    return id;
  }
  function setInterval(fn: any, ms?: number, ...args: any[]): number {
    const id = window.setInterval(fn, ms, ...args);
    _intervals.push(id);
    return id;
  }
  function requestAnimationFrame(fn: any): number {
    const id = window.requestAnimationFrame(fn);
    _frames.push(id);
    return id;
  }

  block1();   // chapter content — fills the empty containers in app.html
  block2();   // the chapters, merged into window.DEMO
  block3();   // the loop engine — chrome, the cut between scenes, the timeline

  return function stopTvDemo(): void {
    _timeouts.forEach(clearTimeout);
    _intervals.forEach(clearInterval);
    _frames.forEach((id) => window.cancelAnimationFrame(id));
    _timeouts.length = _intervals.length = _frames.length = 0;
  };

  /* ══════════════════════════════════════════════════════════════════════
     BLOCK 1 — chapter content — fills the empty containers in app.html
     ══════════════════════════════════════════════════════════════════════ */
  function block1() {
  /* ══════════════════════════════════════════════════════════════════════════
     The three tables are built rather than typed. Each is a list of rows with
     one shape, and a hand-written table is where a column drifts out of line
     with its header and nobody notices until it is on a wall.
     ══════════════════════════════════════════════════════════════════════════ */
  (function () {
      'use strict';
      function $(id) { return document.getElementById(id); }

      /* ── 1 · the product rail ──────────────────────────────────────────────
         Four of the twelve, the first selected. The chips are the master's own:
         pieces to a box, and the cast weight one of them carries — which is what
         makes a box's weight arithmetic rather than a scale reading. */
      var PRODUCTS = [
          ['HUB FLANGE ASSEMBLY W/DAMPER (HF-2280-DAS) (418702)', 'HF-2280-DA', '12/box', '2.845 KG', 1],
          ['HUB FLANGE (HF-2280-EAS) (418698)',                   'HF-2280-EA', '16/box', '2.310 KG', 0],
          ['PINION FLANGE 08R (PF-1140-DAS) (418712)',            'PF-1140-DA', '20/box', '1.706 KG', 0],
          ['BEARING CAP LH (BC-0960-AS) (418720)',                'BC-0960-A',  '24/box', '0.884 KG', 0]
      ];
      $('s1-d1list').innerHTML = PRODUCTS.map(function (p, i) {
          return '<div class="pcard' + (p[4] ? ' sel' : '') + '" data-in="rise" style="--d:'
               + (0.22 + i * 0.11) + 's">'
               + '<div class="nmp">' + p[0] + '</div>'
               + '<div class="cdp">' + p[1] + '</div>'
               + '<div class="tags"><span>Qty: ' + p[2] + '</span>'
               + '<span class="wt">Cast. Wt: ' + p[3] + '</span></div></div>';
      }).join('');

      $('s1-d1tags').innerHTML = [
          ['code', 'HF-2280-DA'], ['mut', 'Driveline OEM (44120)'],
          ['mut', 'SG iron 500/7'], ['acc', '12 / box'], ['acc', '2.845 KG']
      ].map(function (t, i) {
          return '<span class="chip ' + t[0] + '" data-in="pop" style="--d:'
               + (0.42 + i * 0.08) + 's">' + t[1] + '</span>';
      }).join('');

      /* ── the process map ───────────────────────────────────────────────────
         Operation, the machine that runs it, and the table that machine already
         writes into. That last column is the load-bearing one: an operation is
         only CHECKABLE when its machine carries a table source, so a plant that
         feeds nothing has nothing to wait for and the route check stays out of
         the way. It is also why nobody types a result — the machine already did.

           [ op, process, machine, table, flag ]

         OP 60 is optional for this part: recorded and shown, but with no say in
         whether the piece may be inspected onward. */
      var OPS = [
          ['OP 10', 'Rough turn',       'VTL-01',   'dbo.VTL01_Result',   ''],
          ['OP 20', 'Finish turn',      'VTL-02',   'dbo.VTL02_Result',   ''],
          ['OP 30', 'Drill &amp; tap',  'VMC-03',   'dbo.VMC03_Result',   ''],
          ['OP 40', 'Induction harden', 'IH-01',    'dbo.IH01_Result',    ''],
          ['OP 50', 'Grind',            'GRD-02',   'dbo.GRD02_Result',   ''],
          ['OP 60', 'Dynamic balance',  'BAL-01',   'dbo.BAL01_Result',   'opt'],
          ['OP 70', 'Auto gauge',       'GAUGE-01', 'dbo.Gauge01_Result', 'gauge'],
          ['OP 80', 'Leak test',        'LKT-01',   'dbo.LKT01_Result',   '']
      ];
      var FLAG = {
          opt:   '<span class="fl o">Optional</span>',
          gauge: '<span class="fl g">Auto gauge</span>',
          '':    ''
      };
      $('s1-d1map').innerHTML =
          '<div class="mh"><span>#</span><span>OP</span><span>Process</span>'
        + '<span>Machine</span><span>Reads from</span><span></span></div>'
        + OPS.map(function (o, i) {
              return '<div class="mrow' + (o[4] === 'opt' ? ' opt' : '') + '" data-in="rise" '
                   + 'style="--d:' + (0.55 + i * 0.09) + 's">'
                   + '<span class="sq">' + (i + 1) + '</span>'
                   + '<span class="op">' + o[0] + '</span>'
                   + '<span class="pr">' + o[1] + '</span>'
                   + '<span class="mc">' + o[2] + '</span>'
                   + '<span class="tb">' + o[3] + '</span>'
                   + '<span>' + FLAG[o[4]] + '</span></div>';
          }).join('');

      /* ── 2 · the flow ──────────────────────────────────────────────────────
           [ kind, station, enforcement, highlighted ]
         Eddy Current sits at `warn` on purpose: it is the stage that was just
         inserted, and the note underneath is the reason. */
      var STAGES = [
          ['GP12',         'GP12 &middot; GP12-FINAL',        'block', 0],
          ['MPI',          'MPI &middot; MPI-BENCH-1',        'block', 0],
          ['EDDY CURRENT', 'Eddy Current &middot; EDDY-MAIN', 'warn',  1],
          ['LINE PACKING', 'Line Packing &middot; PACK-L2',   'block', 0]
      ];
      $('s1-d2flow').innerHTML = STAGES.map(function (s, i) {
          var d = 0.3 + i * 0.34;
          return (i ? '<div class="arw" data-in="fade" style="--d:' + (d - 0.08) + 's">&rarr;</div>' : '')
               + '<div class="stg' + (s[3] ? ' hi' : '') + '" data-in="rise" style="--d:' + d + 's">'
               + '<div class="sh"><b>' + (i + 1) + '</b><span class="lb">Stage ' + (i + 1) + '</span>'
               + '<span class="xx">&times;</span></div>'
               + '<div class="kind">' + s[0] + '</div>'
               + '<div class="stn"><span class="gp">&#8942;&#8942;</span>' + s[1]
               + '<span class="xx">&times;</span></div>'
               + '<div class="addst">+ Add station</div>'
               + '<div class="enf">If not cleared<span class="sel8'
               + (s[2] === 'warn' ? ' warn9' : '') + '">' + s[2] + '</span></div></div>';
      }).join('')
        + '<div class="arw" data-in="fade" style="--d:1.6s">&rarr;</div>'
        + '<div class="ghost" data-in="fade" style="--d:1.75s"><em>+</em>Add stage</div>';

      /* The three settings the dropdown offers. The note under the flow talks
         about two of them; a viewer who has just watched one stage sit at "warn"
         is owed the third. */
      $('s1-d2leg').innerHTML = [
          ['b9', 'block', 'The piece is refused at this station, and told which stage it has not cleared.'],
          ['w9', 'warn',  'The piece goes on, and the operator is told anyway. Where a new stage starts.'],
          ['o9', 'off',   'The stage is not consulted at all &mdash; recorded, but never a reason to stop.']
      ].map(function (e, i) {
          return '<div class="enfc" data-in="rise" style="--d:' + (2.0 + i * 0.14) + 's">'
               + '<span class="tag9 ' + e[0] + '">' + e[1] + '</span><p>' + e[2] + '</p></div>';
      }).join('');

      /* ── 3 · the sections table ────────────────────────────────────────────
           [ code, name, mode, customer, isDefault ]
         Two of these run in sequence on one line, which is why the note beside
         the table says what it says. */
      var SECTIONS = [
          ['GP12-OP80A', 'GP12 OP80A Final Inspection', 'Multi-area &middot; 1 area',  '', 1],
          ['GP12-OP80B', 'GP12 OP80B Final Inspection', 'Multi-area &middot; 1 area',  '', 0],
          ['GP12-CELL3', 'GP12 Cell 3',                 'Multi-area &middot; 3 areas', 'Driveline OEM', 0],
          ['GP12-FINAL', 'GP12 Final Inspection',       'Standard',                    'Driveline OEM', 0]
      ];
      $('s1-d3secs').innerHTML =
          '<div class="sh8"><span>#</span><span>Section code</span>'
        + '<span>Name &middot; customer</span><span>Mode</span></div>'
        + SECTIONS.map(function (s, i) {
              return '<div class="srow" data-in="rise" style="--d:' + (0.3 + i * 0.16) + 's">'
                   + '<span class="sc">' + (i + 1) + '</span>'
                   + '<span class="sc">' + s[0] + '</span>'
                   + '<span class="nm8">' + s[1]
                   + (s[4] ? '<span class="dflt">DEFAULT</span>' : '')
                   + '<span class="cust' + (s[3] ? '' : ' any') + '">'
                   + (s[3] || '&mdash; any &mdash;') + '</span></span>'
                   + '<span><span class="mode' + (s[2] === 'Standard' ? ' std' : '') + '">'
                   + s[2] + '</span></span></div>';
          }).join('');

      /* ── the inspection plan ───────────────────────────────────────────────
           [ layout, characteristic, instrument, nominal, +tol, -tol, type ]
         Eight instructions, which is what the revision band above claims — and
         the count is taken from this list rather than typed beside it. */
      var INSTR = [
          ['L-01', 'Pilot diameter',      'Bore gauge',          '82.50', '+0.03', '&minus;0.00', 'Dim'],
          ['L-02', 'Flange thickness',    'Micrometer',          '14.20', '+0.10', '&minus;0.10', 'Dim'],
          ['L-03', 'Bolt hole PCD',       'CMM',                 '120.00', '+0.05', '&minus;0.05', 'Dim'],
          ['L-04', 'Bolt hole diameter',  'Plug gauge',          '13.50', '+0.12', '&minus;0.00', 'Dim'],
          ['L-05', 'Face runout',         'Dial indicator',      '0.00',  '+0.04', '&mdash;',     'Dim'],
          ['L-06', 'Surface finish Ra',   'Roughness tester',    '1.60',  '+0.40', '&minus;0.00', 'Dim'],
          ['L-07', 'Case depth at 50 HRC','Hardness traverse',   '1.20',  '+0.30', '&minus;0.20', 'Dim'],
          ['L-08', 'Damper seat',         'Visual &middot; 10&times;', '&mdash;', '&mdash;', '&mdash;', 'Visual']
      ];
      $('s1-d3ins').innerHTML =
          '<div class="ih8"><span>Layout no</span><span>Characteristic</span><span>Instrument</span>'
        + '<span>Nominal</span><span>Tolerance</span><span>Type</span></div>'
        + INSTR.map(function (r, i) {
              return '<div class="irow" data-in="rise" style="--d:' + (0.5 + i * 0.08) + 's">'
                   + '<span class="lay">' + r[0] + '</span>'
                   + '<span class="ch8">' + r[1] + '</span>'
                   + '<span><span class="inst">' + r[2] + '</span></span>'
                   + '<span class="nomi">' + r[3] + '</span>'
                   + '<span class="tol9"><em>' + r[4] + '</em><s>/</s><i>' + r[5] + '</i></span>'
                   + '<span><span class="tp' + (r[6] === 'Visual' ? ' vis' : '') + '">'
                   + r[6] + '</span></span></div>';
          }).join('');

      /* The band says "8 instructions". Make the claim come from the list, so it
         cannot go stale when a row is added or taken away. */
      var band = document.querySelector('#s1-d3 .rev .rl');
      if (band) band.innerHTML = 'Active Revision: <b>Rev 2</b> &mdash; ' + INSTR.length + ' instructions';
  }());


  /* ══════════════════════════════════════════════════════════════════════════
     Chapter 2's builder.

     The whole chapter hangs off one list — MACHINES — because the shift's
     totals, the GP12 rail's tiles and the line-results strip are three views of
     the same run. Typed separately they drift; derived from one list they
     cannot. Scene 5's ECD is likewise interpolated rather than written down.
     ══════════════════════════════════════════════════════════════════════════ */
  (function () {
      'use strict';
      function $(id) { return document.getElementById(id); }

      /* ── the day, and the piece that travels the whole loop ─────────────── */
      var DAY = '18 Sep';
      var QR  = 'HF2280-2609-00417';

      /* ── 1 · inward ────────────────────────────────────────────────────────
         Qty x cast weight is the box's weight. It is arithmetic, not a scale
         reading, which is why the cast weight sits on the product master. */
      var QTY = 148, CAST = 2.845;

      var GATE = [
          ['Gate entry no *', 'GE/U2/26-27/318', 'mn', 0],
          ['DC / invoice no', 'DC-4471',          'mn', 0],
          ['Inward order no', 'IN-260918-07',     'mn ro', 0],
          ['Date &amp; time', '18/09/2026  07:44:10 am', 'mn ro', 0],
          ['GE date',    '18/09/2026',       'mn ro', 0],
          ['Vehicle no', 'TN 41 BX 7290',    'mn ro', 0],
          ['Party',      'Foundry &mdash; Unit 3', 'ro', 1]
      ];
      $('s2-r1gate').innerHTML = GATE.map(function (g, i) {
          return '<div class="' + (g[3] ? 'w2' : '') + '"><div class="lbl">' + g[0] + '</div>'
               + '<div class="fld ' + g[2] + '">' + g[1] + '</div></div>';
      }).join('');

      $('s2-r1prod').innerHTML =
          '<div><div class="lbl">Part name *</div>'
        + '<div class="fld">HUB FLANGE ASSEMBLY W/DAMPER (HF-2280-DAS)</div></div>'
        + '<div><div class="lbl">Part number</div><div class="fld mn ro">HF-2280-DA</div></div>'
        + '<div><div class="lbl">Customer</div><div class="fld ro">Driveline OEM</div></div>'
        + '<div><div class="lbl">Heat no *</div><div class="fld mn">H-2609-K18</div></div>'
        + '<div style="grid-column:span 4"><div class="lbl">Qty &times; cast wt = weight (kg)</div>'
        + '<div class="calc"><span class="bx">' + QTY + '</span><span class="op6">&times;</span>'
        + '<span class="bx">' + CAST.toFixed(3) + '</span><span class="op6">=</span>'
        + '<span class="bx eq">' + (QTY * CAST).toFixed(2) + ' kg</span>'
        + '<span style="font-family:inherit;font-size:18px;color:var(--mute);margin-left:14px">'
        + 'cast weight comes from the product master &mdash; nobody weighs a box</span></div></div>';

      $('s2-r1sum').innerHTML = [
          ['1', 'Items'], [String(QTY), 'Total qty'],
          [(QTY * CAST).toFixed(1), 'Weight (kg)'], ['1', 'Heat nos.']
      ].map(function (s, i) {
          return '<div data-in="pop" style="--d:' + (0.45 + i * 0.1) + 's">'
               + '<div class="vv">' + s[0] + '</div><div class="kk">' + s[1] + '</div></div>';
      }).join('');

      /* ── 2 · the line ──────────────────────────────────────────────────────
           [ op, machine, table, reported, rejected, flag ]
         Every count downstream is derived from this. A piece rejected at a
         machine stops there, so each row's "reported" is the one above it less
         what that one rejected, less anything still in the cell. */
      var MACHINES = [
          ['OP 10', 'VTL-01',   'dbo.VTL01_Result',   148, 0, ''],
          ['OP 20', 'VTL-02',   'dbo.VTL02_Result',   148, 0, ''],
          ['OP 30', 'VMC-03',   'dbo.VMC03_Result',   148, 1, ''],
          ['OP 40', 'IH-01',    'dbo.IH01_Result',    147, 0, ''],
          ['OP 50', 'GRD-02',   'dbo.GRD02_Result',   147, 1, ''],
          ['OP 60', 'BAL-01',   'dbo.BAL01_Result',   146, 0, 'opt'],
          ['OP 70', 'GAUGE-01', 'dbo.Gauge01_Result', 146, 1, 'gauge'],
          ['OP 80', 'LKT-01',   'dbo.LKT01_Result',   143, 1, '']
      ];
      var STARTED   = MACHINES[0][3];
      var REJECTED  = MACHINES.reduce(function (a, m) { return a + m[4]; }, 0);
      var CLEAR     = MACHINES[MACHINES.length - 1][3] - MACHINES[MACHINES.length - 1][4];
      var INCELL    = STARTED - CLEAR - REJECTED;

      $('s2-r2src').innerHTML = MACHINES.length + ' machines &middot; 8 SQL tables &middot; Line 2';

      $('s2-r2tots').innerHTML = [
          ['', STARTED, 'Reported'], ['ok6', CLEAR, 'Route clear'],
          ['bad6', REJECTED, 'Rejected on the line'], ['pend6', INCELL, 'Still in the cell']
      ].map(function (t, i) {
          return '<div class="tot6 ' + t[0] + '" data-in="pop" style="--d:' + (0.3 + i * 0.12) + 's">'
               + '<div class="vv">' + t[1] + '</div><div class="kk">' + t[2] + '</div></div>';
      }).join('');

      var TIMES = ['09:04:12', '09:11:47', '09:19:03', '09:26:31', '09:33:58',
                   '09:36:40', '09:38:20', '09:41:05'];
      $('s2-r2mach').innerHTML = MACHINES.map(function (m, i) {
          var acc = m[3] - m[4];
          return '<div class="mc6' + (m[5] === 'opt' ? ' optm' : '') + '" data-in="rise" style="--d:'
               + (0.55 + i * 0.09) + 's">'
               + '<div class="mh6"><span class="opc">' + m[0] + '</span>'
               + '<span class="mn6">' + m[1] + '</span></div>'
               + '<div class="src6">' + m[2] + '</div>'
               + '<div class="bars"><span class="a6"><i>accepted</i>' + acc + '</span>'
               + '<span class="r6"><i>rejected</i>' + m[4] + '</span>'
               + '<span class="n6"><i>read</i>' + m[3] + '</span></div>'
               + '<div class="ft6">'
               + (m[5] === 'opt' ? 'Optional &mdash; no say in the route'
                  : m[5] === 'gauge' ? 'Auto gauge &middot; parameters graded' : 'last row read')
               + '<span class="wm">' + TIMES[i] + '</span></div></div>';
      }).join('');

      $('s2-r2rules').innerHTML = [
          ['The machine already judged it',
           'One classifier reads the plant&rsquo;s own <code>Status</code> column &mdash; OK, PASS, NG, '
         + 'FAIL and the rest &mdash; and nothing re-derives a verdict from tolerances. '
         + 'Unrecognised text is never rounded up to a pass.'],
          ['A retest is a new row',
           'A rejected piece is commonly re-run, so a table holds several rows per barcode. '
         + 'One record is kept per table and piece &mdash; the <b>latest attempt</b> &mdash; and every '
         + 'attempt still appears in Sync Logs.'],
          ['The route is a veto, not a routing rule',
           'Every mapped operation must have passed before the piece may be inspected onward, '
         + 'whatever its inspection flow says. Two refusals, and a rejection wins over a gap.']
      ].map(function (r, i) {
          return '<div class="rule6" data-in="rise" style="--d:' + (1.5 + i * 0.16) + 's">'
               + '<h5>' + r[0] + '</h5><p>' + r[1] + '</p></div>';
      }).join('');

      /* ── 3 · the scan ──────────────────────────────────────────────────────
         The strip is the shared station-results component: OP code, the pill,
         the machine, when it ran. Its head counts only operations that can hold
         a piece up, so the optional one is out of both halves of "n of m". */
      var SCANNED = 7, CAP = 12;
      $('s2-r3box').innerHTML =
          '<div class="tp6"><span>Active box <b class="mono" style="font-weight:800;color:var(--ink);'
        + 'font-size:19px;margin:0">GP12-260918-04</b></span><b>' + SCANNED + ' / ' + CAP + '</b></div>'
        + '<div class="tk"><i style="--w:' + (100 * SCANNED / CAP).toFixed(1) + '%"></i></div>';

      var required = MACHINES.filter(function (m) { return m[5] !== 'opt'; }).length;
      $('s2-r3meta').innerHTML = required + ' of ' + required
          + ' operations reported &middot; Line 2 &mdash; Flange Cell';

      $('s2-r3ops').innerHTML = MACHINES.map(function (m, i) {
          var opt = m[5] === 'opt';
          var extra = '';
          if (m[5] === 'gauge') {
              extra = '<div class="gch">&#9776; Auto gauge</div>'
                    + '<div class="wrn">&#9888; 2 outside nominal</div>'
                    + '<div class="lnk">View parameters</div>';
          }
          return '<div class="srop ' + (opt ? 'aopt' : 'aok') + '" data-in="rise" style="--d:'
               + (0.75 + i * 0.11) + 's">'
               + '<div class="r1"><span class="oc">' + m[0] + '</span>'
               + '<span class="pill6 ' + (opt ? 'op6' : 'ok6') + '">'
               + (opt ? 'Optional' : 'Accepted') + '</span></div>'
               + '<div class="nm6">' + m[1] + '</div>'
               + '<div class="tm6">' + (opt ? 'Not required for this part'
                                            : DAY + ', ' + TIMES[i]) + '</div>'
               + extra + '</div>';
      }).join('');

      /* The rail's tiles. GP12 sees exactly the route-clear pieces, and its own
         three outcomes have to add back up to them. */
      var HELD = 2, GREJ = 4, GACC = CLEAR - HELD - GREJ;
      $('s2-r3tiles').innerHTML = [
          ['t-tot', CLEAR, 'Total'], ['t-acc', GACC, 'Accepted'],
          ['t-rej', GREJ, 'Rejected'], ['t-hld', HELD, 'On hold']
      ].map(function (t, i) {
          return '<div class="tile6 ' + t[0] + '" data-in="pop" style="--d:' + (0.6 + i * 0.1) + 's">'
               + '<div class="vv">' + t[1] + '</div><div class="kk">' + t[2] + '</div></div>';
      }).join('');

      /* ── 4 · the refusals ──────────────────────────────────────────────────
         Verbatim from the server. FlowGateService builds the first three;
         Gp12InspectionController the hold. The codes beside them are the codes
         it actually returns, because an operator who reports "it said
         ROUTE_INCOMPLETE" has already told you where to look. */
      var REFUSALS = [
          ['ROUTE_INCOMPLETE', 'HF2280-2609-00431',
           'This piece has not been processed at <b>Grind (OP 50)</b> yet &mdash; 1 of ' + required
         + ' line operations are still outstanding. Complete the line route before inspecting it here.',
           'A gap. The piece is fine so far; it simply has not been everywhere it must go.'],
          ['STATION_REJECTED', 'HF2280-2609-00408',
           'This piece was rejected on the line at <b>Leak test (OP 80)</b>. It cannot be inspected onward.',
           'A failure. It wins over a gap, because it names the real problem.'],
          ['FLOW_BLOCKED', 'HF2280-2609-00445',
           'This piece has not passed <b>GP12 &middot; GP12-FINAL</b> yet &mdash; required before this '
         + 'station by the part&rsquo;s inspection flow.',
           'The flow, not the line. Stations inside one stage are joined with &ldquo;or&rdquo; &mdash; '
         + 'they are alternatives.'],
          ['PIECE_ON_HOLD', 'HF2280-2609-00422',
           'This piece is on hold. Release it from <b>Held Pieces</b> to inspect it again.',
           'A hold takes no verdict and is plant-wide: held at one section, refused at every section.']
      ];
      $('s2-r4grid').innerHTML = REFUSALS.map(function (r, i) {
          return '<div class="rf6" data-in="rise" style="--d:' + (0.3 + i * 0.22) + 's">'
               + '<div class="rh6"><span class="cd6">' + r[0] + '</span>'
               + '<span class="qr6">' + r[1] + '</span></div>'
               + '<div class="rb6">' + r[2] + '</div>'
               + '<div class="rn6">' + r[3] + '</div></div>';
      }).join('');

      $('s2-r4warn').innerHTML =
          '<div class="rh6"><span class="cd6">WARNING &mdash; allowed through</span>'
        + '<span class="qr6">' + QR + '</span></div>'
        + '<div class="rb6" style="font-size:22px">This piece has not passed '
        + '<b>Eddy Current &middot; EDDY-MAIN</b> yet &mdash; required before this station by the '
        + 'part&rsquo;s inspection flow.</div>'
        + '<div class="rn6" style="padding-bottom:15px">The stage is set to <b>warn</b>, so the piece '
        + 'goes on and the operator is told anyway. This is what a newly inserted stage is set to '
        + 'while the pieces made before it existed drain through.</div>';

      /* ── 5 · the benches ───────────────────────────────────────────────────
         Two pieces on the bench: one still waiting to be out-scanned, one that
         has been and can now be judged. */
      $('s2-r5n').innerHTML = 'GP12 &rarr; MPI &rarr; Eddy Current';

      /* Each bench takes what the one before it passed. Written this way so the
         chain that ends in chapter 3's ten sealed boxes starts from a number
         already on screen in the GP12 rail, rather than from a typed one. */
      var MPI_IN = GACC, MPI_OUT = MPI_IN - 1;
      var EDDY_IN = MPI_OUT, EDDY_OUT = EDDY_IN - 1;
      $('s2-r5mpin').innerHTML  = MPI_IN + ' in &middot; ' + MPI_OUT + ' accepted';
      $('s2-r5eddyn').innerHTML = EDDY_IN + ' in &middot; ' + EDDY_OUT + ' accepted';
      var PIECES = [
          ['Piece 1', 'HF2280-2609-00417', 1],
          ['Piece 2', 'HF2280-2609-00418', 0]
      ];
      $('s2-r5mpi').innerHTML = PIECES.map(function (p, i) {
          return '<div class="pcbox' + (p[2] ? ' done6' : '') + '" data-in="rise" style="--d:'
               + (0.3 + i * 0.16) + 's">'
               + '<div class="p1"><span class="no6">' + p[0] + '</span>'
               + '<span class="chip ok" style="margin-left:auto;font-size:15px;padding:4px 11px">'
               + '&#10003; GP12 passed</span></div>'
               + '<div class="nm6">HUB FLANGE ASSEMBLY W/DAMPER (HF-2280-DAS)</div>'
               + '<div class="qr6">' + p[1] + '</div>'
               + (p[2]
                   ? '<div class="vd"><b class="a">&#10003; ACCEPT</b><b class="r">&#10007; REJECT</b></div>'
                   : '<div class="wait6">&#9744; Awaiting out-scan &mdash; scan this piece again to '
                   + 'enable the verdict.</div>')
               + '</div>';
      }).join('');

      /* ── the lab ───────────────────────────────────────────────────────────
         The hardness traverse is five real points, and the effective case depth
         is INTERPOLATED from them at the cutoff exactly as the product does it:
         find the pair that straddles the cutoff, walk between them linearly,
         round to 2dp. Typing "1.49" would have been easier and would have made
         the number decoration; computing it means the traverse and the answer
         cannot disagree, and the reader can check it. */
      var CUTOFF = 50;                       // HRC, from the plan's L-07
      var SPEC = [1.00, 1.50];               // 1.20 +0.30 / -0.20
      var TRAVERSE = [[0.5, 58.4], [0.9, 55.1], [1.3, 51.6], [1.7, 48.2], [2.1, 44.0]];

      function ecd(points, cutoff) {
          for (var i = 0; i < points.length - 1; i++) {
              var a = points[i], b = points[i + 1];
              if ((a[1] >= cutoff && b[1] <= cutoff) || (a[1] <= cutoff && b[1] >= cutoff)) {
                  if (a[1] === b[1]) return Math.round(a[0] * 100) / 100;
                  var frac = (cutoff - a[1]) / (b[1] - a[1]);
                  return Math.round((a[0] + frac * (b[0] - a[0])) * 100) / 100;
              }
          }
          return null;
      }
      var ECD = ecd(TRAVERSE, CUTOFF);
      var inSpec = ECD >= SPEC[0] && ECD <= SPEC[1];

      /* which two rows straddle the cutoff — highlighted, so the interpolation
         is visible rather than asserted */
      var lo = -1;
      for (var i = 0; i < TRAVERSE.length - 1; i++) {
          if (TRAVERSE[i][1] >= CUTOFF && TRAVERSE[i + 1][1] <= CUTOFF) { lo = i; break; }
      }

      var travHtml =
          '<span class="hd6">Depth</span>'
        + TRAVERSE.map(function (p, i) {
              return '<span class="' + (i === lo || i === lo + 1 ? 'strad' : '') + '">'
                   + p[0].toFixed(1) + '</span>';
          }).join('')
        + '<span class="hd6">HRC</span>'
        + TRAVERSE.map(function (p, i) {
              return '<span class="' + (i === lo || i === lo + 1 ? 'strad' : '') + '">'
                   + p[1].toFixed(1) + '</span>';
          }).join('');

      var LAB = [
          ['Induction hardness', 'traverse &middot; location A', inSpec,
           '<div class="trav" style="grid-template-columns:repeat(6,1fr)">'
         + travHtml + '</div>'
         + '<div class="ecd">Read at the <em>' + CUTOFF + ' HRC</em> cutoff, interpolated between '
         + 'the two rows that straddle it &mdash; <b>ECD ' + ECD.toFixed(2) + ' mm</b>, against '
         + SPEC[0].toFixed(2) + ' &ndash; ' + SPEC[1].toFixed(2) + ' from plan row L-07.</div>'],
          ['Grinder burn', 'nital etch &middot; 3 zones', true,
           '<div style="flex:1 1 auto">'
         + '<div class="labrow"><span class="k6">Etchant &middot; ethanolic HCl &middot; NaOH</span>'
         + '<span class="v6">per procedure</span></div>'
         + '<div class="labrow" style="margin-top:8px"><span class="k6">Zones showing burn</span>'
         + '<span class="v6">0 / 3</span></div>'
         + '<div class="labrow" style="margin-top:8px"><span class="k6">Rejection reason</span>'
         + '<span class="lim">required only when rejecting</span></div></div>'],
          ['Millipore', 'gravimetric &amp; SEM-EDAX', true,
           '<div style="flex:1 1 auto">'
         + '<div class="labrow"><span class="k6">Test E &mdash; contamination</span>'
         + '<span class="v6">4.2</span><span class="lim">mg / 1000 cm&sup2; &middot; limit 8.0</span></div>'
         + '<div class="labrow" style="margin-top:8px"><span class="k6">Test G &mdash; largest particle</span>'
         + '<span class="v6">182</span><span class="lim">&micro;m &middot; limit 400</span></div>'
         + '<div class="labrow" style="margin-top:8px"><span class="k6">Fe by weight</span>'
         + '<span class="v6">25.4</span><span class="lim">%</span></div></div>']
      ];
      $('s2-r5lab').innerHTML = LAB.map(function (l, i) {
          return '<div class="lab6" style="flex:1 1 0" data-in="rise">'
               + '<div class="lh6"><span class="tt6">' + l[0] + '</span>'
               + '<span class="sub6">' + l[1] + '</span>'
               + '<span class="vr6 chip ' + (l[2] ? 'ok' : 'bad') + '">'
               + (l[2] ? '&#10003; Accepted' : '&#10007; Rejected') + '</span></div>'
               + '<div class="lb6' + (i === 0 ? ' col9' : '') + '">' + l[3] + '</div></div>';
      }).join('');
      /* the beats, set after the fact so the template strings stay readable */
      [].slice.call(document.querySelectorAll('#s2-r5lab .lab6')).forEach(function (n, i) {
          n.style.setProperty('--d', (0.35 + i * 0.28) + 's');
      });
  }());


  /* ══════════════════════════════════════════════════════════════════════════
     Chapter 3's builder.

     The container's totals are arithmetic on the box, and the box's arithmetic
     is the product master's cast weight — the same 2.845 KG chapter 2 used to
     weigh the incoming box. Ten sealed boxes of twelve is 120 pieces and
     341.40 kg, and both are computed here so a slip, a total and a summary
     cannot say three different things.
     ══════════════════════════════════════════════════════════════════════════ */
  (function () {
      'use strict';
      function $(id) { return document.getElementById(id); }

      var PART   = 'HF-2280-DA';
      var CAST   = 2.845;          // kg, from the product master
      var PERBOX = 12;
      var QR     = 'HF2280-2609-00417';
      var CTR    = 'CTR-260918-02';
      var VEH    = 'TN 41 BX 7290';

      /* ── 1 · the open box ──────────────────────────────────────────────────
         Nine of twelve, mid-shift. The list is generated from the count so the
         "9 items" chip, the bar and the rows can never disagree. */
      var IN_BOX = 9, START_SN = 129;
      var TIMES = ['12:41', '12:43', '12:46', '12:48', '12:51', '12:55', '12:58', '13:02', '13:05'];

      $('s3-p1n').innerHTML = 'box PK-260918-11';
      $('s3-p1bar').innerHTML =
          '<div class="t2"><span>' + IN_BOX + ' / ' + PERBOX + ' scanned</span><b>'
        + Math.round(100 * IN_BOX / PERBOX) + '%</b></div>'
        + '<div class="tk2"><i style="--w:' + (100 * IN_BOX / PERBOX).toFixed(1) + '%"></i></div>';
      $('s3-p1cnt').innerHTML = IN_BOX + ' items';
      $('s3-p1rows').innerHTML = Array.apply(null, Array(IN_BOX)).map(function (_, i) {
          var sn = START_SN + i;
          return '<div class="prow" data-in="rise" style="--d:' + (0.6 + i * 0.08) + 's">'
               + '<b>' + (i + 1) + '</b>'
               + '<span class="qc">HF2280-2609-00' + sn + '</span>'
               + '<span class="sn2">SN: 00' + sn + '</span>'
               + '<span class="tm2">' + TIMES[i] + '</span></div>';
      }).join('');

      $('s3-p1info').innerHTML = [
          ['Part', 'HUB FLANGE ASSEMBLY W/DAMPER', 0],
          ['Part no', PART, 1],
          ['Customer', 'Driveline OEM', 0],
          ['Qty / box', String(PERBOX), 1],
          ['Cast wt', CAST.toFixed(3) + ' KG', 1],
          ['Box wt', (PERBOX * CAST).toFixed(2) + ' KG', 1],
          ['Supplier', 'Foundry &mdash; Unit 3', 0]
      ].map(function (r) {
          return '<div class="rw"><span class="k3">' + r[0] + '</span>'
               + '<span class="v3' + (r[2] ? ' mn2' : '') + '">' + r[1] + '</span></div>';
      }).join('');

      /* ── the container ─────────────────────────────────────────────────────
         Ten slips, each a sealed box. Every figure below is derived from the
         three constants above — a slip's weight, the totals row, and the
         summary panel all resolve to the same arithmetic. */
      var SLIPS = 10;
      var boxWt = PERBOX * CAST;
      var rows = [];
      for (var i = 0; i < SLIPS; i++) {
          rows.push(['PK-260918-' + ('0' + (i + 1)).slice(-2), PERBOX, boxWt]);
      }
      var totQty = rows.reduce(function (a, r) { return a + r[1]; }, 0);
      var totWt  = rows.reduce(function (a, r) { return a + r[2]; }, 0);

      $('s3-p1slips').innerHTML =
          '<div class="sh3"><span>#</span><span>License plate</span>'
        + '<span class="rr3">Qty</span><span class="rr3">Box wt</span></div>'
        + rows.map(function (r, i) {
              return '<div class="slrow" data-in="rise" style="--d:' + (0.55 + i * 0.07) + 's">'
                   + '<span class="ix">' + (i + 1) + '</span>'
                   + '<span class="lp">' + r[0] + '</span>'
                   + '<span class="qy">' + r[1] + '</span>'
                   + '<span class="wt3">' + r[2].toFixed(2) + '</span></div>';
          }).join('')
        + '<div class="slrow tot3" data-in="rise" style="--d:1.3s"><span></span>'
        + '<span>' + SLIPS + ' slips</span><span class="qy">' + totQty + '</span>'
        + '<span class="wt3">' + totWt.toFixed(2) + '</span></div>';

      $('s3-p1gate').innerHTML = [
          ['Entry no', 'OGE/U2/26-27/205'], ['Tran no', 'WB/U2/26-27/144'],
          ['Load wt', '2430'], ['Weighments', '1'], ['Vehicle', VEH]
      ].map(function (r) {
          return '<div class="rw"><span class="k3">' + r[0] + '</span>'
               + '<span class="v3 mn2">' + r[1] + '</span></div>';
      }).join('');

      $('s3-p1sum').innerHTML = [
          ['Container no', CTR], ['Total slips', String(SLIPS)],
          ['Total qty', String(totQty)], ['Total wt (kg)', totWt.toFixed(2)]
      ].map(function (r) {
          return '<div class="rw"><span class="k3">' + r[0] + '</span>'
               + '<span class="v3 mn2">' + r[1] + '</span></div>';
      }).join('');

      /* ── 2 · the journey ───────────────────────────────────────────────────
         Four stages, in the order the part's flow declares them, each with the
         verdict and the record that carries it. The piece is in box 06, which
         is sealed and loaded — which is what lets the tail below run all the
         way to the gate. */
      $('s3-p2recent').innerHTML = [
          ['HUB FLANGE ASSEMBLY W/DAMPER (HF-2280-DAS)', QR, 'ok', 'Packed', '18 Sept, 12:31', 1],
          ['HUB FLANGE ASSEMBLY W/DAMPER (HF-2280-DAS)', 'HF2280-2609-00419', 'bad', 'Eddy &middot; Rejected', '18 Sept, 11:59', 0],
          ['HUB FLANGE ASSEMBLY W/DAMPER (HF-2280-DAS)', 'HF2280-2609-00422', 'warn', 'GP12 &middot; On hold', '18 Sept, 09:56', 0],
          ['PINION FLANGE 08R (PF-1140-DAS)', 'PF1140-2609-00088', 'ok', 'GP12 &middot; Accepted', '18 Sept, 09:31', 0]
      ].map(function (r, i) {
          return '<div class="rc3' + (r[5] ? ' sel3' : '') + '" data-in="rise" style="--d:'
               + (0.22 + i * 0.1) + 's">'
               + '<div class="n3">' + r[0] + '</div><div class="q3">' + r[1] + '</div>'
               + '<div class="b3"><span class="chip ' + r[2]
               + '" style="font-size:15px;padding:4px 11px">' + r[3] + '</span>'
               + '<span class="tm3">' + r[4] + '</span></div></div>';
      }).join('');

      $('s3-p2meta').innerHTML = [
          ['Serial', '00417'], ['Customer', 'Driveline OEM (44120)'],
          ['Heat no', 'H-2609-K18'], ['Line', 'Line 2 &mdash; Flange Cell'],
          ['QR date', '18 Sept 2026']
      ].map(function (m) {
          return '<div><div class="k3">' + m[0] + '</div><div class="v3">' + m[1] + '</div></div>';
      }).join('');

      /*   [ stage, station, verdict, kind, when, detail ]  */
      var JOURNEY = [
          ['Line route', '7 of 7 operations &middot; Line 2', 'Accepted', 'ok',
           '18 Sept, 09:41:05', 'last reported at LKT-01 &middot; 2 readings outside nominal, noted'],
          ['GP12', 'GP12 &middot; GP12-FINAL', 'Accepted', 'ok',
           '18 Sept, 09:47:12', 'box GP12-260918-04 &middot; operator OP_14'],
          ['MPI', 'MPI &middot; MPI-BENCH-1', 'Accepted', 'ok',
           '18 Sept, 11:15:38', 'in-scanned 11:12 &middot; out-scanned 11:15 &middot; batch of 2'],
          ['Eddy Current', 'Eddy Current &middot; EDDY-MAIN', 'Accepted', 'ok',
           '18 Sept, 11:58:04', 'operator OP_09'],
          ['Line Packing', 'Line Packing &middot; PACK-L2', 'Packed', 'acc',
           '18 Sept, 12:31:50', 'box PK-260918-06 &middot; slip printed']
      ];
      $('s3-p2tl').innerHTML = JOURNEY.map(function (s, i) {
          return '<div class="tlrow' + (i === JOURNEY.length - 1 ? ' last3' : '')
               + '" data-in="rise" style="--d:' + (0.45 + i * 0.22) + 's">'
               + '<div class="tlc"><b class="sq3">' + (i + 1) + '</b>'
               + '<div><div class="kn">' + s[0] + '</div>'
               + '<div class="st3">' + s[1] + '</div></div>'
               + '<span class="chip ' + s[3] + ' vv3" style="margin-left:auto">' + s[2] + '</span>'
               + '<div class="dt3">' + s[4] + '<br>' + s[5] + '</div></div></div>';
      }).join('');

      $('s3-p2tail').innerHTML = [
          ['Container', CTR], ['Vehicle', VEH],
          ['Gate entry', 'OGE/U2/26-27/205'], ['Dispatched', '18 Sept, 16:52']
      ].map(function (t) {
          return '<div><div class="k3">' + t[0] + '</div><div class="v3">' + t[1] + '</div></div>';
      }).join('');

      /* ── 3 · the grid ──────────────────────────────────────────────────────
         Eight of a hundred and forty-eight, chosen so all four outcomes are on
         screen at once: accepted and shipped, rejected downstream, held, and
         still in progress. The Traceability screen keeps Accept / Reject as its
         column vocabulary — deliberately not the Accepted / Rejected used on
         the inspection screens, which is a distinction worth not smoothing out.

           [ serial, at, gp12, mpi, eddy, overall, packed, container, dispatched ]  */
      var TOTAL = 148;
      $('s3-p3n').innerHTML = 'HF-2280-DA &middot; 18/09/2026 &middot; 1 &ndash; 50 of ' + TOTAL;

      var A = ['Accept', 'a3'], R = ['Reject', 'r3'], H = ['Hold', 'h3'],
          P = ['Pending', 'p3'], N = ['&mdash;', 'n3'];
      var GRID = [
          ['00417', '09:47:12', A, A, A, ['Accepted', 'o3'],   'Yes', CTR, '16:52'],
          ['00418', '09:48:41', A, A, A, ['Accepted', 'o3'],   'Yes', CTR, '16:52'],
          ['00419', '09:50:06', A, A, R, ['Rejected', 'r3'],   'No',  '',  ''],
          ['00420', '09:52:19', A, A, A, ['Accepted', 'o3'],   'Yes', CTR, '16:52'],
          ['00421', '09:54:33', A, A, A, ['Accepted', 'o3'],   'Yes', CTR, '16:52'],
          ['00422', '09:56:02', H, N, N, ['On hold', 'h3'],    'No',  '',  ''],
          ['00423', '09:58:47', A, A, A, ['Accepted', 'o3'],   'Yes', CTR, '16:52'],
          ['00424', '10:01:15', A, P, N, ['In-progress', 'p3'],'No',  '',  '']
      ];
      function pill(x) { return '<span class="tp3 ' + x[1] + '">' + x[0] + '</span>'; }
      $('s3-p3grid').innerHTML =
          '<div class="th3"><span>#</span><span>Measured at</span><span>Serial no</span>'
        + '<span>Part code</span><span>GP12-FINAL</span><span>MPI</span><span>Eddy</span>'
        + '<span>Overall</span><span>Packed</span><span>Container</span><span>Vehicle</span>'
        + '<span>Dispatched</span></div>'
        + GRID.map(function (g, i) {
              var out = !!g[7];
              return '<div class="tb3" data-in="rise" style="--d:' + (0.32 + i * 0.1) + 's">'
                   + '<span class="ix3">' + (i + 1) + '</span>'
                   + '<span class="mn3">' + g[1] + '</span>'
                   + '<span class="mn3"><b>HF2280-2609-' + g[0] + '</b></span>'
                   + '<span class="mn3">' + PART + '</span>'
                   + '<span>' + pill(g[2]) + '</span><span>' + pill(g[3]) + '</span>'
                   + '<span>' + pill(g[4]) + '</span><span>' + pill(g[5]) + '</span>'
                   + '<span class="' + (g[6] === 'Yes' ? '' : 'dash') + '">' + g[6] + '</span>'
                   + '<span class="mn3' + (out ? '' : ' dash') + '">' + (g[7] || '&mdash;') + '</span>'
                   + '<span class="mn3' + (out ? '' : ' dash') + '">' + (out ? VEH : '&mdash;') + '</span>'
                   + '<span class="mn3' + (out ? '' : ' dash') + '">' + (g[8] || '&mdash;') + '</span>'
                   + '</div>';
          }).join('');

      /* ── the row we hand back ──────────────────────────────────────────────
         One statement per verdict, on a row the plant's own machine already
         wrote. It never inserts, so re-running it changes nothing and no loop
         can form between the table we read and the table we write. */
      $('s3-p3sql').innerHTML =
          '<span class="cmt3">-- one statement per verdict &middot; never an INSERT</span><br>'
        + '<span class="kw3">UPDATE</span> dbo.OP80B_Result<br>'
        + '&nbsp;&nbsp;&nbsp;<span class="kw3">SET</span> Status = <span class="str3">\'PASS\'</span><br>'
        + '<span class="kw3">WHERE</span> Barcode = <span class="str3">\'' + QR + '\'</span>';

      $('s3-p3rules').innerHTML = [
          ['It updates, never inserts',
           'One field, on a row the machine already wrote. Re-running it is harmless; an insert '
         + 'would not have been.'],
          ['No matching row is not an error',
           'The verdict is already ours and every screen reads it from there. The piece is marked '
         + 'done rather than retried forever.'],
          ['A failure never reaches the operator',
           'They are holding a piece and cannot act on it. Unwritten verdicts stay flagged and a '
         + 'sweep picks them up on the next pass.']
      ].map(function (r, i) {
          return '<div class="wbc" data-in="rise" style="--d:' + (1.6 + i * 0.14) + 's">'
               + '<h5>' + r[0] + '</h5><p>' + r[1] + '</p></div>';
      }).join('');
  }());
  }

  /* ══════════════════════════════════════════════════════════════════════
     BLOCK 2 — the chapters, merged into window.DEMO
     ══════════════════════════════════════════════════════════════════════ */
  function block2() {
  /* The three chapters, merged. Each scene carries its own chapter's step pills,
     caption strip and interstitial wording, because those change between chapters
     and the engine applies them per scene. */
  var CHAPTERS = [
      {
          product:  'Shopfloor MES',
          where:    ['Part', 'HF-2280-DA'],
          steps:    ['The part', 'The route', 'Where &amp; to what spec'],
          title:    'Shopfloor MES — describe the plant',
          subtitle: 'The part, the machines that make it, and the inspection it has to clear.',
          consign: [
              { k: 'Part',     v: 'HF-2280-DA' },
              { k: 'Customer', v: 'Driveline OEM', sm: true },
              { k: 'Line',     v: 'Line 2 &middot; Flange Cell', sm: true },
              { k: 'Ops',      v: '8' },
              { k: 'Qty/box',  v: '12' }
          ],
          scenes: [
              { tx: { n: 'What this shows',
                      h: 'Every piece answers<b>for where it has been</b>',
                      li: ['The plant is described once &mdash; operations, machines, inspection stages',
                           'Then every scan is judged against it, on the shop floor, in real time',
                           'And afterwards any piece can be asked where it went and what said so'] },
                dur: 7000 },
              { id: 's1-d1', step: 1, dur: 14500,
                t: 'Describe the part once',
                s: 'Its operations, the machine that runs each one, and the table that machine already writes to. An operation can be marked optional &mdash; recorded and shown, but with no say in whether the piece may go on.' },
              { tx: { n: 'Next',
                      h: 'The route it<b>has to clear</b>',
                      li: ['Stages in order &mdash; GP12, MPI, Eddy Current, Line Packing',
                           'Each one blocks the piece, or warns and lets it through',
                           'Stations inside a stage are alternatives; stages are not'] },
                dur: 5600 },
              { id: 's1-d2', step: 2, dur: 14000,
                t: 'Four stages, in order',
                s: 'Drag them, and set what happens when a piece arrives without having cleared one. Eddy Current was just added, so it is set to <b>warn</b> until the pieces made before it existed have drained.' },
              { tx: { n: 'Next',
                      h: 'A stage is a rule.<b>A section is a place.</b>',
                      li: ['One stage can happen in several areas, each with its own boxes and holds',
                           'And the numbers it is measured against are a versioned plan',
                           'A new revision starts a new record &mdash; the old one stays readable'] },
                dur: 5600 },
              { id: 's1-d3', step: 3, dur: 14500,
                t: 'Where it happens, and to what number',
                s: 'Sections are independent inspection areas &mdash; standard or multi-area, per customer or plant-wide. The plan beside them carries the nominal and the tolerance, under a revision that can be superseded but never quietly edited.' }
          ]
      },
      {
          product:  'Shopfloor MES',
          where:    ['Shift 1', '18/09/2026'],
          steps:    ['Inward', 'The line', 'GP12', 'Refusals', 'The benches'],
          title:    'Shopfloor MES — run the shift',
          subtitle: 'One box in at the gate, one piece through the route, one shift on the screen.',
          consign: [
              { k: 'Part',  v: 'HF-2280-DA' },
              { k: 'Shift', v: '1 &middot; 08:30&ndash;16:30', sm: true },
              { k: 'Day',   v: '18/09/2026', sm: true },
              { k: 'Line',  v: 'Line 2 &middot; Flange Cell', sm: true },
              { k: 'Box',   v: 'GP12-260918-04', sm: true }
          ],
          scenes: [
              { tx: { n: 'Next',
                      h: 'A box at the gate,<b>and a heat number that follows it</b>',
                      li: ['Qty &times; cast weight is the box weight &mdash; nobody puts a box on a scale',
                           'The heat number travels with every piece cast from it',
                           'And the inward inspection fires the moment the box is submitted'] },
                dur: 5800 },
              { id: 's2-r1', step: 1, dur: 14000,
                t: 'The box arrives',
                s: 'Gate entry, invoice, vehicle &mdash; filled once for the box. Then the part, the heat number, and the count. The weight is arithmetic from the product master, so it cannot be keyed wrong.' },
              { tx: { n: 'Next',
                      h: 'The machines report<b>before anybody inspects</b>',
                      li: ['Each machine already writes its results to its own plant table',
                           'Those tables are read on a watermark &mdash; SMES writes nothing back to them',
                           'And the shift&rsquo;s counts are what came back, not what somebody logged'] },
                dur: 5800 },
              { id: 's2-r2', step: 2, dur: 15000,
                t: 'The line reports first',
                s: 'Eight machines, eight tables, read continuously. A retest is a new row and the latest attempt stands; unrecognised status text is counted separately and never rounded up to a pass.' },
              { tx: { n: 'Next',
                      h: 'Scan one piece,<b>see everywhere it has been</b>',
                      li: ['The whole upstream route arrives with the scan &mdash; stations and gauges alike',
                           'A reading outside nominal is shown, and never overrules the machine',
                           'Twelve to a box, then close the box and print its slip'] },
                dur: 5800 },
              { id: 's2-r3', step: 3, dur: 16000,
                t: 'One scan, the whole route',
                s: 'Every operation the piece passed, when, and what said so &mdash; including the auto gauge&rsquo;s own parameters. The optional operation is shown in full and counts toward nothing.' },
              { tx: { n: 'Next',
                      h: 'Four ways a piece<b>is stopped at the scanner</b>',
                      li: ['A gap and a failure are different problems &mdash; and read differently',
                           'A hold is plant-wide: held at one section, refused at every section',
                           'And a stage can be set to warn instead, which lets it through out loud'] },
                dur: 5800 },
              { id: 's2-r4', step: 4, dur: 15000,
                t: 'What the gate refuses',
                s: 'These are the server&rsquo;s own messages, not a paraphrase &mdash; each names the operation or the stage that stopped the piece, so the operator can act on it without calling anybody.' },
              { tx: { n: 'Next',
                      h: 'Some tests run on<b>every piece. Some on one.</b>',
                      li: ['MPI and Eddy Current judge each piece as it comes off the line',
                           'A verdict is unlocked only after the piece is scanned back out',
                           'Hardness, grinder burn and cleanliness are sampled, and go to a lab report'] },
                dur: 5800 },
              { id: 's2-r5', step: 5, dur: 15500,
                t: 'The benches, and the lab',
                s: 'At the bench a piece is scanned in and scanned out, so a verdict belongs to a piece that has actually been examined. In the lab the case depth is interpolated off the traverse, not typed.' }
          ]
      },
      {
          product:  'Shopfloor MES',
          where:    ['Piece', '00417'],
          steps:    ['Pack &amp; ship', 'One piece', 'Every piece'],
          title:    'Shopfloor MES — answer for it',
          subtitle: 'The piece leaves the plant, and everything that judged it stays behind.',
          consign: [
              { k: 'Piece',     v: 'HF2280-2609-00417', sm: true },
              { k: 'Box',       v: 'PK-260918-06', sm: true },
              { k: 'Container', v: 'CTR-260918-02', sm: true },
              { k: 'Pieces',    v: '148' },
              { k: 'Day',       v: '18/09/2026', sm: true }
          ],
          scenes: [
              { tx: { n: 'Next',
                      h: 'Pieces into boxes,<b>boxes into a container</b>',
                      li: ['A box is scanned shut and prints its own packing slip',
                           'The slip is then scanned onto a container, against its gate entry',
                           'And the weight is arithmetic all the way down &mdash; nothing is estimated'] },
                dur: 5800 },
              { id: 's3-p1', step: 1, dur: 15000,
                t: 'Pack it, then load it',
                s: 'Twelve to a box at 2.845 KG a piece, so a box weighs 34.14 KG and ten of them weigh 341.40 &mdash; the same cast weight the incoming box was measured by, used again on the way out.' },
              { tx: { n: 'Next',
                      h: 'Scan any piece,<b>and it tells you where it went</b>',
                      li: ['Every stage it cleared, when, and who or what said so',
                           'Including the machines &mdash; before anybody inspected it',
                           'Down to the box, the container and the gate it left through'] },
                dur: 5800 },
              { id: 's3-p2', step: 2, dur: 15000,
                t: 'One piece, its whole journey',
                s: 'The line route first, because a piece exists from its first machine report &mdash; then each inspection stage in the order the part&rsquo;s flow declares them, and the box and container that carried it out.' },
              { tx: { n: 'Next',
                      h: 'The same question,<b>asked of a whole day</b>',
                      li: ['Every piece against every stage, in one grid, exportable',
                           'A gap reads as a gap and a failure reads as a failure',
                           'And the verdict is written back onto the plant&rsquo;s own row'] },
                dur: 5800 },
              { id: 's3-p3', step: 3, dur: 16000,
                t: 'Every piece, every stage',
                s: 'One row per piece and one column per station, for a part and a day. Underneath, the GP12 verdict goes back to the machine&rsquo;s own table &mdash; one field, on a row the plant already wrote.' }
          ]
      }
  ];

  /* true: a card before every scene. false: only the one that opens each chapter. */
  var CARD_BEFORE_EVERY_SCENE = false;

  window.DEMO = {
      bare:  false,
      speed: 1,
      product: CHAPTERS[0].product,
      where:   CHAPTERS[0].where,
      steps:   CHAPTERS[0].steps,
      title:   CHAPTERS[0].title,
      subtitle: CHAPTERS[0].subtitle,
      consign: CHAPTERS[0].consign,
      scenes: CHAPTERS.reduce(function (all, c) {
          var kept = 0;
          return all.concat(c.scenes.filter(function (s) {
              // The first card of a chapter always stays: without it a chapter
              // starts mid-flow with nothing saying what is being shown.
              return !s.tx || CARD_BEFORE_EVERY_SCENE || !kept++;
          }).map(function (s) {
              s.nav = c.steps;
              s.consign = c.consign;
              s.title = c.title;
              s.subtitle = c.subtitle;
              return s;
          }));
      }, [])
  };
  }

  /* ══════════════════════════════════════════════════════════════════════
     BLOCK 3 — the loop engine — chrome, the cut between scenes, the timeline
     ══════════════════════════════════════════════════════════════════════ */
  function block3() {
  /* ── inlined from shared/engine.js ───────────────── */
  /* ══════════════════════════════════════════════════════════════════════════
     The loop engine, shared by every TV demo.
     Inlined into each demo by build.js.

     A demo declares window.DEMO before this runs:

       DEMO = {
         product:  'Warehouse Stores',        // beside the wordmark
         where:    ['Finished Goods Store', 'FG01'],
         steps:    ['Pick & Bin', 'Floor view', 'Rack — place'],
         title:    'Warehouse Stores — into the rack',   // shown on interstitials
         subtitle: 'One pallet, from inspection to its cell.',
         consign:  [{ k: 'Item', v: '1002' }, ...],      // the strip, right of the caption
         scenes:   [
           { tx: { n: 'Next', h: 'Where is <b>item 1001</b>?', li: ['…','…'] }, dur: 6000 },
           { id: 'sc1', step: 1, dur: 12000, t: 'headline', s: 'sub-line' },
           …
         ]
       }

     A scene with `tx` is an interstitial: the engine renders it into the single
     #tx slide, so a demo never has to hand-write one. A scene with `id` shows
     that element. `step` is 1-based into DEMO.steps; omit it on an interstitial.

     Durations are generous on purpose: under about six seconds is unreadable
     from the far side of a room, where nobody is going to rewind.
     ══════════════════════════════════════════════════════════════════════════ */
  (function () {
      'use strict';

      var D = window.DEMO;
      var stage = document.getElementById('stage');
      var area  = document.getElementById('area');

      function el(tag, cls, html) {
          var e = document.createElement(tag);
          if (cls) e.className = cls;
          if (html != null) e.innerHTML = html;
          return e;
      }

      /* ══ chrome ═══════════════════════════════════════════════════════════
         Built here rather than repeated in every demo's markup: three copies of
         a top bar is three places to fix a wording change. */
      var bar = el('header', 'bar');
      bar.innerHTML =
          '<div class="brand"><span>' + D.product + '</span></div>' +
          '<nav class="steps"></nav>' +
          '<div class="where">' + D.where[0] + ' <em>' + D.where[1] + '</em></div>';
      var logo = document.getElementById('logo');
      if (logo) { bar.querySelector('.brand').insertBefore(logo, bar.querySelector('.brand span')); logo.hidden = false; }

      /* The step pills, and the consignment strip below, can change between
         chapters when several demos are played from one file. Both are rebuilt
         only when their content actually changes — rebuilding every scene would
         restart the pills' transitions and flicker on every cut. */
      var nav = bar.querySelector('.steps'), navNow = null;
      function setNav(labels) {
          var sig = labels.join('|');
          if (sig === navNow) return;
          navNow = sig;
          nav.innerHTML = '';
          labels.forEach(function (label, i) {
              if (i) nav.appendChild(el('i'));
              var p = el('span', 'step', '<b>' + (i + 1) + '</b>' + label);
              p.dataset.step = String(i + 1);
              nav.appendChild(p);
          });
      }
      setNav(D.steps);
      stage.insertBefore(bar, area);

      // the interstitial slide — one element, re-filled per text scene
      var tx = el('section', 'scene');
      tx.id = 'tx';
      tx.innerHTML =
          '<div class="tx">' +
              '<svg class="deco" viewBox="0 0 100 100" aria-hidden="true">' +
                '<g fill="none" stroke="currentColor" stroke-width="1.6">' +
                  '<circle cx="100" cy="0" r="24"/><circle cx="100" cy="0" r="38"/>' +
                  '<circle cx="100" cy="0" r="52"/><circle cx="100" cy="0" r="66"/>' +
                  '<circle cx="100" cy="0" r="80"/><circle cx="100" cy="0" r="94"/>' +
                '</g></svg>' +
              '<div class="n" data-in="rise" style="--d:.1s"></div>' +
              '<h1 data-in="rise" style="--d:.28s"></h1>' +
              '<ul></ul>' +
          '</div>';
      area.appendChild(tx);
      var txN = tx.querySelector('.n'), txH = tx.querySelector('h1'), txL = tx.querySelector('ul');

      var wipe = el('div', 'wipe');
      wipe.id = 'wipe';
      area.appendChild(wipe);

      var cap = el('footer', 'cap');
      cap.innerHTML = '<div class="txt" id="capTxt"><h2 id="capT">&nbsp;</h2><p id="capS">&nbsp;</p></div>' +
                      '<div class="consign"></div>';
      stage.appendChild(cap);
      var strip = cap.querySelector('.consign'), stripNow = null;
      function setConsign(fields) {
          var sig = JSON.stringify(fields);
          if (sig === stripNow) return;
          stripNow = sig;
          strip.innerHTML = fields.map(function (f) {
              return '<div class="f"><div class="k">' + f.k + '</div>' +
                     '<div class="v' + (f.sm ? ' sm' : '') + '">' + f.v + '</div></div>';
          }).join('');
      }
      setConsign(D.consign);

      var prog = el('div', 'prog', '<i id="progBar"></i>');
      stage.appendChild(prog);

      var hint = el('div', null, 'SPACE pause &middot; &larr; &rarr; scene &middot; F fullscreen');
      hint.id = 'hint';
      document.body.appendChild(hint);

      /* Embedded in a page rather than filling a panel: the keyboard hint is
         somebody else's furniture, and a hidden cursor over part of a web page
         is a bug. Both are right on a wall and wrong in an iframe. */
      /* A touchscreen has no SPACE and no arrow keys, and a hint naming them is
         worse than none: it says the board cannot be driven at all. */
      var touch = !!(window.matchMedia && window.matchMedia('(pointer: coarse)').matches);
      if (touch) hint.innerHTML = 'TAP pause &middot; SWIPE scene';

      var framed = window.top !== window.self;
      if (framed) {
          hint.style.display = 'none';
          document.documentElement.style.cursor = 'default';
          document.body.style.cursor = 'default';
      }

      /* ══ the loop ═════════════════════════════════════════════════════════ */
      /* ?bare drops the text cards along with the caption strip: in a page the
         copy beside the frame is already doing that job. Guarded — if a demo
         were ever all cards, filtering them all out would leave nothing to
         play, so the unfiltered list wins. */
      // ?bare for a page that wants it, D.bare for a build that always does.
      var bare = D.bare || new URLSearchParams(location.search).has('bare');
      /* Everything plays at this rate. Not just the cuts: the scenes are
         choreographed over about nine seconds, so speeding the cuts alone would
         show half-built scenes and never the payoff. */
      var SPEED = D.speed || 1;
      if (bare) {
          document.body.classList.add('bare');
          // DEMO.scenes itself, not a private copy: what plays and what the
          // page says it plays have to be the same list, or a check reads the
          // declaration and passes while the loop does something else.
          var lean = D.scenes.filter(function (s) { return !s.tx; });
          if (lean.length) D.scenes = lean;
      }
      var SCENES = D.scenes;
      var TOTAL = SCENES.reduce(function (a, s) { return a + s.dur; }, 0);

      var progBar = document.getElementById('progBar');
      var capT = document.getElementById('capT');
      var capS = document.getElementById('capS');
      var capTxt = document.getElementById('capTxt');
      var idx = -1, sceneStart = 0, paused = false, clock = 0;

      function show(i) {
          var sc = SCENES[i];
          SCENES.forEach(function (s) {
              if (s.id) document.getElementById(s.id).classList.remove('on');
          });
          tx.classList.remove('on');

          if (sc.tx) {
              txN.innerHTML = sc.tx.n || 'Next';
              txH.innerHTML = sc.tx.h;
              txL.innerHTML = (sc.tx.li || []).map(function (t, k) {
                  return '<li data-in="rise" style="--d:' + (0.55 + k * 0.22) + 's"><i></i><span>' + t + '</span></li>';
              }).join('');
              // Re-adding .on after display:none restarts every animation in the
              // slide, which is what makes two interstitials in a row replay.
              void tx.offsetWidth;
              tx.classList.add('on');
          } else {
              document.getElementById(sc.id).classList.add('on');
          }
          document.body.classList.toggle('on-tx', !!sc.tx);

          setNav(sc.nav || D.steps);
          setConsign(sc.consign || D.consign);
          [].slice.call(nav.querySelectorAll('.step')).forEach(function (p) {
              p.classList.toggle('on', +p.dataset.step === sc.step);
          });
          // innerHTML, not textContent: these are authored captions, and with
          // textContent an "&mdash;" printed as six literal characters across
          // the bottom of the screen.
          capT.innerHTML = sc.tx ? (sc.title || D.title) : sc.t;
          capS.innerHTML = sc.tx ? (sc.subtitle || D.subtitle) : sc.s;
          capTxt.classList.remove('swap');
          void capTxt.offsetWidth;
          capTxt.classList.add('swap');

          /* The scene's animations have just been (re)started by the class
             change. Setting playbackRate scales each one's delay and duration
             together, whichever of CSS, an inline --d or a builder's computed
             value it came from — so the choreography compresses instead of being
             cut off. A frame later, because they do not exist until then. */
          if (SPEED !== 1 && document.getAnimations) {
              requestAnimationFrame(function () {
                  document.getAnimations().forEach(function (a) { a.playbackRate = SPEED; });
              });
          }
      }

      function go(i) {
          idx = (i + SCENES.length) % SCENES.length;
          sceneStart = clock;
          wipe.classList.remove('run');
          void wipe.offsetWidth;
          wipe.classList.add('run');
          // Swap under the sweep, not in front of it. The sweep is a CSS
          // animation and is sped up with everything else, so this waits for the
          // same fraction of it however fast the cut is.
          setTimeout(function () { show(idx); }, 330 / SPEED);
      }

      var last = 0;
      function frame(now) {
          if (!last) last = now;
          var dt = now - last;
          last = now;
          if (!paused) {
              clock += dt;
              if (idx < 0 || clock - sceneStart >= SCENES[idx].dur / SPEED) go(idx + 1);
              // progress across the WHOLE loop, so a viewer can see it is finite
              var done = SCENES.slice(0, idx).reduce(function (a, s) { return a + s.dur; }, 0)
                       + Math.min((clock - sceneStart) * SPEED, SCENES[idx].dur);
              progBar.style.width = (100 * (done % TOTAL) / TOTAL).toFixed(2) + '%';
          }
          requestAnimationFrame(frame);
      }
      requestAnimationFrame(frame);

      /* ══ fit any panel with one transform — no re-layout at 4K or 1366 ═════ */
      /* Turn the board a quarter turn when the panel is taller than it is wide.
         Unrotated, a 16:9 stage on a phone or a portrait-mounted screen shrinks to
         a strip with two thirds of the glass left black. Nothing in the loop is
         pointer-driven, so the rotation costs nothing. Set false for a panel that
         is genuinely portrait-first. */
      var ROTATE_IN_PORTRAIT = true;

      function fit() {
          /* visualViewport, not innerHeight: on Android the URL bar and the
             on-screen keyboard move the former and not always the latter. */
          var vv = window.visualViewport;
          var w = (vv && vv.width)  || window.innerWidth;
          var h = (vv && vv.height) || window.innerHeight;
          var turn = ROTATE_IN_PORTRAIT && h > w;
          var s = turn ? Math.min(h / 1920, w / 1080)
                       : Math.min(w / 1920, h / 1080);
          stage.style.transform = 'translate(-50%, -50%)'
                                + (turn ? ' rotate(90deg)' : '')
                                + ' scale(' + s + ')';
          document.body.classList.toggle('turned', turn);
      }
      window.addEventListener('resize', fit);
      window.addEventListener('orientationchange', fit);
      if (window.visualViewport) window.visualViewport.addEventListener('resize', fit);
      fit();

      /* ══ keep the panel awake ═════════════════════════════════════════════
         Without this most machines sleep mid-afternoon and the booth goes dark.
         Re-requested on visibility change: the lock is dropped when the tab is
         hidden and is NOT restored on its own. */
      // The sentinel is held in scope on purpose: drop the reference and some
      // implementations release the lock when it is collected.
      var lock = null;
      function wake() {
          if (!('wakeLock' in navigator)) return;
          navigator.wakeLock.request('screen').then(function (l) { lock = l; }).catch(function () {});
      }
      document.addEventListener('visibilitychange', function () {
          if (document.visibilityState === 'visible') wake();
      });
      wake();

      /* ══ for whoever is standing next to it ═══════════════════════════════ */
      document.addEventListener('keydown', function (e) {
          if (e.code === 'Space') {
              e.preventDefault();
              paused = !paused;
              document.body.classList.toggle('paused', paused);
              hint.textContent = paused
                  ? (touch ? 'PAUSED — TAP to resume' : 'PAUSED — SPACE to resume')
                  : (touch ? 'TAP pause · SWIPE scene' : 'SPACE pause · ← → scene · F fullscreen');
              // Freeze every animation, not just the clock, or the scene keeps
              // playing under a stopped timeline.
              stage.querySelectorAll('*').forEach(function (n) {
                  n.style.animationPlayState = paused ? 'paused' : '';
              });
          } else if (e.key === 'ArrowRight') { go(idx + 1); }
          else if (e.key === 'ArrowLeft')    { go(idx - 1); }
          else if (e.key.toLowerCase() === 'f') {
              if (document.fullscreenElement) document.exitFullscreen();
              else document.documentElement.requestFullscreen().catch(function () {});
          }
      });
  /* ══ the same three controls, for a panel that is a touchscreen ═══════
         Routed back through the keydown handler above rather than duplicated,
         so pause and scene stepping can only ever behave one way. */
      (function () {
          var x0 = 0, y0 = 0, t0 = 0;
          function press(code, key) {
              document.dispatchEvent(new KeyboardEvent('keydown', { code: code, key: key, bubbles: true }));
          }
          document.addEventListener('touchstart', function (e) {
              var t = e.changedTouches[0];
              x0 = t.clientX; y0 = t.clientY; t0 = Date.now();
          }, { passive: true });
          document.addEventListener('touchend', function (e) {
              var t = e.changedTouches[0];
              var dx = t.clientX - x0, dy = t.clientY - y0;
              if (Date.now() - t0 > 700) return;                    // a rest, not a gesture
              if (Math.abs(dx) > 60 && Math.abs(dx) > Math.abs(dy)) {
                  if (dx < 0) press('ArrowRight', 'ArrowRight');
                  else        press('ArrowLeft',  'ArrowLeft');
              } else if (Math.abs(dx) < 16 && Math.abs(dy) < 16) {
                  press('Space', ' ');
              }
          }, { passive: true });
      }());
  }());
  }
}
